
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'trainer.dockerfile', '.', '-t', 'trainer:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'trainer:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'tester.dockerfile', '.', '-t', 'tester:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'tester:latest']
