
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'trainer.dockerfile', '.', '-t', 'gcr.io/dtumlops-tweet-sentiment/github.com/hallamaria1997/02476_mlops/trainer:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtumlops-tweet-sentiment/github.com/hallamaria1997/02476_mlops/trainer:latest']


